# Lesson 3.14-3.15 Notes and Homework
> This is the jupyter notebook for lessons 3.14-3.15.
 
- toc: true
- badges: true
- comments: true
- permalink: /lesson7
- categories: [jupyter, Student-Guided Lessons]

<style>
    .coolCode {
        color: #FFFFFF;
        font-family: monospace;
        border: 1px solid #404040;
        border-radius: 3px;
        background-color: #212121;
        padding: 1px 5px;
        font-size: 20px
    }
</style>

### wget https://raw.githubusercontent.com/aidenhuynh/CS_Swag/master/_notebooks/2022-11-30-randomvalues.ipynb

# Libraries

* A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. 
* These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.
* A library may also contain documentation, configuration data, message templates, classes, and values, etc.

### Why are libraries important?
* Using Libraries makes Python Programming simpler and convenient for the programmer. 
* One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs. 
* Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

### A few libraries that simplify coding processes:
* **Pillow** allows you to work with images.
* **Tensor Flow** helps with data automation and monitors performance.
* **Matplotlib** allows you to make 2D graphs and plots.

The AP Exam Refrence Sheet itself is a library!
![Screenshot 2022-12-11 221853](https://user-images.githubusercontent.com/51098969/206974627-af98327c-d95d-4459-be67-cbaa3faaaa98.jpg)

## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

### API’s
* An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used. 
* An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.

### Activity: Walkthrough with NumPy
* Install NumPy on VSCode:
    1. Open New Terminal In VSCode:
    2. pip3 install --upgrade pip
    3. pip install numpy 
 
REMEMBER: When running library code cells use Python Interpreter Conda (Version 3.9.12)
 
### Example of using NumPy for arrays:

In [1]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Example of using NumPy for derivatives:

In [2]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


## Random Values

* Random number generation (RNG) produces a random number (crazy right?)
    - This means that a procedure with RNG can return different values even if the parameters (inputs) do not change
* CollegeBoard uses <code class="coolCode">RANDOM(A, B)</code>, to return an integer between integers <code class="coolCode">A</code> and <code class="coolCode">B</code>.
    - RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10
    - In Python, this would be <code class="coolCode">random.randint(A, B)</code>, after importing Python's "random" library (<code class="coolCode">import random</code>)
    - JavaScript's works a little differently, with <code class="coolCode">Math.random()</code> returning a value between 0 and 1.
        - To match Python and CollegeBoard, you could make a procedure like [this](https://stackoverflow.com/a/7228322)

#### CollegeBoard Example: What is the possible range of values for *answ3*
![CollegeBoard](https://i.ibb.co/Wt90Hbz/Screen-Shot-2022-12-12-at-7-27-58-AM.png)


#### Convert the following procedure to Python, then determine the range of outputs if n = 5.
<pre>
<font color=white>
PROCEDURE Dice(n)
	sum ← 0
	REPEAT UNTIL n = 0
		sum ← sum + RANDOM(1, 6)
		n ← n - 1
	RETURN sum
</font>
</pre>


In [10]:
import random

def Dice(n):
    # Code here
    sum = 0
    while n >0:
        sum = sum + random.randint(1,6)
        n -= 1
    return sum
    
Dice(5) # Will output a range of 5 to 30

18

## Homework
1. Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier).

2. Using NumPy and only coding in python cell, find the answer to the following questions:
    a. What is the derivative of 2x^5 - 6x^2 + 24x?
    b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

3. Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

In [7]:
import random

even = []
odd = []

def randomNumber():
    n = random.randint(1,100)
    return n

i = 0
while i ==0:
    rNumber = randomNumber()
    inputNumber = input("Type anything to start, type 'stop' to show random numbers")
    if inputNumber == "stop":
        i +=1
    if rNumber % 2 == 0:
        even.append(rNumber)
    else:
        odd.append(rNumber)

print("Even: ", *even)
print("Odd: ", *odd)


Even:  74 54 44 28 14 26 34 38 100 88 34
Odd:  85 67 41 71


In [14]:
import numpy as np
print("a.")
polynomial = np.poly1d([2, 0,0,-6, 1,0])
print("Polynomial: f(x)=\n", polynomial)

Pderivative = polynomial.deriv()
print("Derivative: f'(x)=\n", Pderivative)

print("b.")
polynomial2 = np.poly1d([6.5,0,2,0,0])
print("Polynomial: f(x)=\n", polynomial2)

Pderivative2 = polynomial2.deriv()
print("Derivative: f'(x)=\n", Pderivative2)

print("When x=9,  f(x)'=", Pderivative2(9))

a.
Polynomial: f(x)=
    5     2
2 x - 6 x + 1 x
Derivative: f'(x)=
     4
10 x - 12 x + 1
b.
Polynomial: f(x)=
      4     2
6.5 x + 2 x
Derivative: f'(x)=
     3
26 x + 4 x
When x=9,  f(x)'= 18990.0


In [22]:
import random

dogCat = ["dog", "cat"]

print(random.choices(dogCat, k=20))

['dog', 'dog', 'cat', 'dog', 'dog', 'dog', 'dog', 'cat', 'dog', 'dog', 'cat', 'cat', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat', 'cat', 'cat']


## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

## Hacks Submission:
**Chainer**: A library that helps build networks. It can help programmers code by easily being able to run a GPU with a few lines of code, and by its ability to use multiple GPUs very without much effort. 

**Scikit-learn**: A library that helps to analyze different types of data. It helps programmers code by making data analysis much more simpler and efficient.